### ISSUE TITLE
codex/Divinity on join crashes

### ISSUE THREAD

**Issue by Hitman477** [magemonkeystudio/codex#34]
Is there an existing issue for this?

I have searched the existing issues

Have you tried to reproduce this without OP?

I have tested without OP

Current Behavior

when player join, console starts spam errors
Expected Behavior

everything is fine
Steps To Reproduce

    start server
    player join
    errors

Environment

- Server Software: paper 1.21.1
- Fabled Version: fabled-1.0.1-R0.6-20240917.023949-1
- Codex Version: codex-1.0.1-R0.3-20240917.024013-1
- Divinity Version: divinity-1.0.1-R0.3-20240924.052643-1
- Plugins:
[16:06:37] [ServerMain/INFO]: [PluginInitializerManager] Initialized 25 plugins
[16:06:37] [ServerMain/INFO]: [PluginInitializerManager] Paper plugins (3):
 - Codex (1.0.1-R0.3-SNAPSHOT), Divinity (1.0.1-R0.3-SNAPSHOT), Fabled (1.0.1-R0.6-SNAPSHOT)
[16:06:37] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (22):
 - BetonQuest (2.1.3), Chatty (2.19.14), CinematicStudio (2.0.1-indev-1), Citizens (2.0.35-SNAPSHOT (build 3583)), DecentHolograms (2.8.11), Essentials (2.20.1), FastAsyncWorldEdit (2.11.3-SNAPSHOT-930;7192e14), ImageFrame (1.7.10.0), InteractionVisualizer (1.18.11.1), LoneLibs (1.0.59), LuckPerms (5.4.141), ModelEngine (R4.0.7), MythicMobs (5.7.2-${CI_COMMIT_SHORT_SHA}), PlaceholderAPI (2.11.7-DEV-200), ProtocolLib (5.3.0-SNAPSHOT-732), SkinsRestorer (15.4.3), TAB (4.1.8), Towny (0.100.4.0), Vault (1.7.3-b131), ViaBackwards (5.0.3), ViaVersion (5.0.3), WorldGuard (7.0.12+829a4a4)

[2024-10-06-15.log](https://github.com/user-attachments/files/17269490/2024-10-06-15.log)

**Comment by Hitman477** [comment]
tried new Divinity R8.
still errors
[latest.log](https://github.com/user-attachments/files/17269554/latest.log)

**Comment by Travja** [comment]
I'm not currently having issues, though I haven't ever heard of or used Leaf. Leaf itself might be getting in the way. I'll do some digging

**Comment by Hitman477** [comment]
https://github.com/Winds-Studio/Leaf/
This is their repo

**Comment by Hitman477** [comment]
Also i met an error in fabled. May i drop it here?

It was when im using /class bind (no choosing skill) with an item.

**Comment by Travja** [comment]
Create a ticket on magemonkeystudio/fabled

**Comment by Hitman477** [comment]
got that.
Any news about the problem above?

**Comment by Travja** [comment]
Long story short... I'm resolving some of these issues, but at the core, there is a lot more going on here and the way our plugin is set up prevents us from providing any logical support for Leaf at this point in time. I don't have the bandwidth to make the changes necessary to provide support right now either. I'm going to go ahead and close this for now and just recommend you use either Paper or Spigot instead.
